### ISSUE TITLE
Make the homepage using HTML, CSS 

### ISSUE THREAD

**Issue by praptisharma28** [praptisharma28/FossAlgo#1]
Start the local server, by following readme. You must be seeing a django server running. 
If you are aware of django, you need to create a template directory inside your Django app to store your HTML files.

In your Django app directory, create a folder named templates.

Fossalgo/
    templates/
            homepage.html

Create a CSS file: In the static directory, add the CSS file.

Create the static/css/style.css file.

Create view, create url and you are good to go.

The homepage should look like this, with leetcode logo instead of codechef.
![image](https://github.com/user-attachments/assets/76667149-e4f9-4143-99cd-dea2b0e34256)

**Comment by Harsh-Trivedii** [comment]
Hi! I'd like to work on this issue. Could you please assign it to me?

**Comment by praptisharma28** [comment]
Go ahead @Harsh-Trivedii
