### ISSUE TITLE
Enhance Readme 

### ISSUE THREAD

**Issue by praptisharma28** [praptisharma28/FossAlgo#3]

**Comment by aniruddhaadak80** [comment]
Assign me please @praptisharma28 . I am working on it .

**Comment by anoushka-10** [comment]
Please assign me this issue @praptisharma28

**Comment by praptisharma28** [comment]
> Assign me please @praptisharma28 . I am working on it .

Thanks @aniruddhaadak80 , would have liked more additions, may be tags to make it look attractive as well. 
If you are willing to contribute anything else other than readme, please open an another issue, until then I am assigning this one to @anoushka-10
